baseURL = "http://localhost:1313/"
languageCode = "pt-br"
title = "Rafa o Cunha"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  showReadingTime = true
  env = "production"
  enableSearch = true

  # ativa thumbnails nas listas (cards)
  showPostNavLinks = true
  showPageThumbnail = true
  showImageInList = true

  # Homepage simples
  [params.homeInfoParams]
    #homeInfoParams = { Title = "Rafael Cunha", Content = "Meu hub de tecnologia" }
    ShowRecent = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

#############################
# MENU PRINCIPAL
#############################

[menu]

  [[menu.main]]
    name = "R&D Notes"
    url  = "/rnd-notes/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url  = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Insights"
    url  = "/insights/"
    weight = 3

  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 4

  [[menu.main]]
    name = "Search"
    url  = "/search/"
    weight = 5

